Nit fixes on documentation
bitcoindevkit/bdk-ffi pull request #338
Opened 2023-04-11 12:03 UTC by tusharxoxoxo

### Description
It mainly includes typos, sentence constructions, and punctuations. Fixes are reported by Grammarly.

### Notes to the reviewers

### Changelog notice

### Checklists

#### All Submissions:

* [ ] I've signed all my commits
* [ ] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [ ] I ran `cargo fmt` and `cargo clippy` before committing
Checklists
All Submissions:
 I've signed all my commits
 I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
 I ran cargo fmt and cargo clippy before committing
#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2023-04-11 14:14 UTC, thunderbiscuit requested changes
Thanks for your contribution!

Good little fixes in there, but not all of them are good IMO. Let's remove a few and this will be ready to go.

2023-04-11 14:14 UTC, thunderbiscuit commented on README.md
> +2. Update mapping `bdk.udl` file with new a `interface`
This one doesn't make sense.

2023-04-11 14:14 UTC, thunderbiscuit commented on README.md
> +Each supported language and the platform(s) it's packaged for have their own directories. The Rust code in this project is in the bdk-ffi directory. It is a wrapper around the [bdk] library to expose
I'm ok with the `uniformly` change. The rest is better as is IMO.

2023-04-11 16:52 UTC, tusharxoxoxo commented
@thunderbiscuit I have made the changes as per your suggestions.

2023-04-11 18:12 UTC, thunderbiscuit commented
Perfect. Can you squash those two commits into one? After that I'll give the ACK.

2023-04-11 21:05 UTC, tusharxoxoxo commented
@thunderbiscuit I have squashed it

2023-04-11 23:54 UTC, thunderbiscuit commented
Yes it just means approving the PR.

Can you tell us more about who you are and why you decided to contribute to the repos? I see you made similar grammarly small fixes to bdk.

2023-04-11 23:54 UTC, thunderbiscuit approved these changes
ACK 38c078b70fbc634af60282d1f20d551e07664280

2023-04-13 14:17 UTC, thunderbiscuit commented
I can't rebase and push for you in this case because you're using the master branch on your fork for this PR.

Can you rebase to pick up the latest changes on master and force push?

2023-04-17 20:12 UTC, notmandatory commented
@tusharxoxoxo, as with your other PRs in the `bdk` and `bdk-cli` repo I'm closing this PR because the changes don't constitute a meaningful improvement. Feel free to open a new PR if you'd like to make any more substantial additions or fixes.

2023-04-17 20:12 UTC, closed without merging

2023-04-17 20:19 UTC, tusharxoxoxo commented
Okay sure

On Tue, 18 Apr, 2023, 1:42 am Steve Myers, ***@***.***> wrote:

> Closed #338 <https://github.com/bitcoindevkit/bdk-ffi/pull/338>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoindevkit/bdk-ffi/pull/338#event-9028760361>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3DYSVJWT5HHSE6OEWPY5LXBWP2XANCNFSM6AAAAAAW2FT53A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>