feat(descriptor): add bip-86 template
bitcoindevkit/bdk-ffi pull request #388
Opened 2023-08-03 21:06 UTC by reez

### Description

### Notes to the reviewers

### Changelog notice

### Checklists

#### All Submissions:

* [ ] I've signed all my commits
* [ ] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [ ] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2023-08-11 01:53 UTC, notmandatory commented
Looks good! we should make a local swift package with this branch and try it out in your example ios wallet.

2023-08-11 02:35 UTC, reez commented
> Looks good! we should make a local swift package with this branch and try it out in your example ios wallet.

Can do!

2023-08-11 15:08 UTC, thunderbiscuit requested changes
Tested. Looks good! Would you mind adding to the tests that start on line 266? Just for completeness since the other 3 templates are tested/showcased there.

I also think we can remove the comment on line 304; the templates are now showing correct coin types on testnet.

Otherwise ready to go IMO.

2023-08-11 16:13 UTC, reez commented
> Looks good! we should make a local swift package with this branch and try it out in your example ios wallet.

Just created a local swift package off of this branch and tried it out in the [iOS wallet](https://github.com/reez/BDKSwiftExampleWallet) creating and using a bip-86 wallet, and it worked great.

![Simulator Screenshot - iPhone 14 Pro - 2023-08-11 at 11 09 06](https://github.com/bitcoindevkit/bdk-ffi/assets/6657488/de4acf7c-2ef1-4cd9-a91f-f1ee12e7aac9)

2023-08-11 17:37 UTC, reez commented
> Tested. Looks good! Would you mind adding to the tests that start on line 266? Just for completeness since the other 3 templates are tested/showcased there.
> 
> I also think we can remove the comment on line 304; the templates are now showing correct coin types on testnet.
> 
> Otherwise ready to go IMO.

Definitely! The code is updated now, and tests pass ✅.
- Added tests for bip-86
- removed comment on line 304

  *Note*
  I changed line 307 
  `let template_private_84 = Descriptor::new_bip84(master, KeychainKind::External, Network::Testnet);` 
  to 
  `let template_private_84 = Descriptor::new_bip84(master.clone(), KeychainKind::External, Network::Testnet);` 
  just because of the ownership rules since I added the line 
  `let template_private_86 = Descriptor::new_bip86(master, KeychainKind::External, Network::Testnet);` 
  after that line. 
  The other quick option was to just add `.clone()` to both of those lines, but I kept things similar to how it was before and just made the last of those lines (`template_private_86`) not have `.clone()`.

2023-08-15 15:42 UTC, thunderbiscuit approved these changes
Tested ACK c3e8469686ff0c9aace45d0578e3d4162ea236a8.

2023-08-15 15:43 UTC, thunderbiscuit commented
@reez do you mind rebasing this? I'll merge right away. Sorry this took so long to review/get in.

2023-08-15 17:10 UTC, merged